### ISSUE TITLE
メンバーの追加 / 管理権限の変更

### ISSUE THREAD

**Issue by pathtrk** [chun1979/Cesium_SIP_Chun1#3]
@chun1979 お疲れ様です

@yuheioggu さんをレポジトリへ[招待](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#inviting-a-team-or-person)いただけますでしょうか？

ひとまず `Write` の権限があれば十分かと思います。

また、もし僕 (@pathtrk) を管理者にしてくだされば、このあたりの対応はこちらで可能です。

**Comment by chun1979** [comment]
取り急ぎ招待しました．

**Comment by chun1979** [comment]
管理者にしちゃおうかなと思ったんですが，メンバー管理ってどこでしたっけ（時間がないため後ほど対応します）

**Comment by pathtrk** [comment]
@chun1979 ありがとうございます！

権限の設定は[こちら](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository)をご覧になってみて下さい。

お手数おかけしますが、よろしくお願い致します！

**Comment by chun1979** [comment]
これはもしかして大学アカウントなので無料で有料相当のことが出来ているけど，所有者とコラボレータ以上のことが出来ないかもしれません．もしかしたら後藤さんのほうで立ち上げていただいたほうがいいかも？
https://docs.github.com/ja/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository
（管理者の仕事が，あとはSIM3Dのリンクのみであればこちらで対応可能そうですが）

**Comment by pathtrk** [comment]
@chun1979 ご確認ありがとうございます！承知しました

僕の方でこちらの内容を引き継いだrepositoryを用意しまして、オーナー権限でご招待してみます
